version: "3"

services:
  app:
    build: .
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html/app
    networks:
      - app-net
  nginx:
    image: nginx:1.17-alpine
    depends_on:
      - app
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html/app
      - ./.docker/nginx:/etc/nginx/conf.d
    networks:
      - app-net
  mysql:
    image: mysql:5.7.34
    networks:
      - app-net
    ports:
      - 33066:3306
    volumes:
      - .docker/mysql/var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=docker
      - MYSQL_ROOT_PASSWORD=secret

networks:
  app-net:
    driver: bridge